version: "3.8"

services:
  ws-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - NEXT_BACKEND_PORT=8000
      - NEXT_OPENAI_KEY=${NEXT_OPENAI_KEY}
      - NEXT_TWILIO_SID=${NEXT_TWILIO_SID}
      - NEXT_TWILIO_AUTH_TOKEN=${NEXT_TWILIO_AUTH_TOKEN}
      - NEXT_VIRTUAL_NUMBER=${NEXT_VIRTUAL_NUMBER}
      - NEXT_APP_URL=${NEXT_APP_URL}
      - NEXT_PUBLIC_CONVEX_URL=${NEXT_PUBLIC_CONVEX_URL}
      - NEXT_GEMINI_API_KEY=${NEXT_GEMINI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8000/testing",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
